import {ICON_CLASS} from 'react-native-stralom-components';

const icons = [
  {id: 1, name: 'plane', class: ICON_CLASS.SimpleLineIcons},
  {id: 2, name: 'trophy', class: ICON_CLASS.SimpleLineIcons},
  {id: 3, name: 'event', class: ICON_CLASS.SimpleLineIcons},
  {id: 4, name: 'screen-desktop', class: ICON_CLASS.SimpleLineIcons},
  {id: 5, name: 'chemistry', class: ICON_CLASS.SimpleLineIcons},
  {id: 6, name: 'speedometer', class: ICON_CLASS.SimpleLineIcons},
  {id: 7, name: 'shield', class: ICON_CLASS.SimpleLineIcons},
  {id: 8, name: 'magic-wand', class: ICON_CLASS.SimpleLineIcons},
  {id: 9, name: 'graduation', class: ICON_CLASS.SimpleLineIcons},
  {id: 10, name: 'ghost', class: ICON_CLASS.SimpleLineIcons},
  {id: 11, name: 'game-controller', class: ICON_CLASS.SimpleLineIcons},
  {id: 12, name: 'eyeglass', class: ICON_CLASS.SimpleLineIcons},
  {id: 13, name: 'envelope-open', class: ICON_CLASS.SimpleLineIcons},
  {id: 14, name: 'bell', class: ICON_CLASS.SimpleLineIcons},
  {id: 15, name: 'badge', class: ICON_CLASS.SimpleLineIcons},
  {id: 16, name: 'anchor', class: ICON_CLASS.SimpleLineIcons},
  {id: 17, name: 'wallet', class: ICON_CLASS.SimpleLineIcons},
  {id: 18, name: 'speech', class: ICON_CLASS.SimpleLineIcons},
  {id: 19, name: 'puzzle', class: ICON_CLASS.SimpleLineIcons},
  {id: 20, name: 'printer', class: ICON_CLASS.SimpleLineIcons},
  {id: 21, name: 'present', class: ICON_CLASS.SimpleLineIcons},
  {id: 22, name: 'picture', class: ICON_CLASS.SimpleLineIcons},
  {id: 23, name: 'globe', class: ICON_CLASS.SimpleLineIcons},
  {id: 24, name: 'drop', class: ICON_CLASS.SimpleLineIcons},
  {id: 25, name: 'diamond', class: ICON_CLASS.SimpleLineIcons},
  {id: 26, name: 'cup', class: ICON_CLASS.SimpleLineIcons},
  {id: 27, name: 'calculator', class: ICON_CLASS.SimpleLineIcons},
  {id: 28, name: 'wrench', class: ICON_CLASS.SimpleLineIcons},
  {id: 29, name: 'umbrella', class: ICON_CLASS.SimpleLineIcons},
  {id: 30, name: 'trash', class: ICON_CLASS.SimpleLineIcons},
  {id: 31, name: 'home', class: ICON_CLASS.SimpleLineIcons},
  {id: 32, name: 'graph', class: ICON_CLASS.SimpleLineIcons},
  {id: 33, name: 'chart', class: ICON_CLASS.SimpleLineIcons},
  {id: 34, name: 'heart', class: ICON_CLASS.SimpleLineIcons},
  {id: 35, name: 'flag', class: ICON_CLASS.SimpleLineIcons},
  {id: 36, name: 'credit-card', class: ICON_CLASS.SimpleLineIcons},
  {id: 37, name: 'settings', class: ICON_CLASS.SimpleLineIcons},
  {id: 38, name: 'star', class: ICON_CLASS.SimpleLineIcons},
  {id: 39, name: 'paper-plane', class: ICON_CLASS.SimpleLineIcons},

  {id: 40, name: 'at-sharp', class: ICON_CLASS.Ionicons},
  {id: 41, name: 'bandage-outline', class: ICON_CLASS.Ionicons},
  {id: 42, name: 'basket-outline', class: ICON_CLASS.Ionicons},
  {id: 43, name: 'basketball-outline', class: ICON_CLASS.Ionicons},
  {id: 44, name: 'beer-outline', class: ICON_CLASS.Ionicons},
  {id: 45, name: 'bicycle-outline', class: ICON_CLASS.Ionicons},
  {id: 46, name: 'boat-outline', class: ICON_CLASS.Ionicons},
  {id: 47, name: 'bug-outline', class: ICON_CLASS.Ionicons},
  {id: 48, name: 'bus-outline', class: ICON_CLASS.Ionicons},
  {id: 49, name: 'business-outline', class: ICON_CLASS.Ionicons},
  {id: 50, name: 'bus-outline', class: ICON_CLASS.Ionicons},
  {id: 51, name: 'cafe-outline', class: ICON_CLASS.Ionicons},
  {id: 52, name: 'calculator-outline', class: ICON_CLASS.Ionicons},
  {id: 53, name: 'call-outline', class: ICON_CLASS.Ionicons},
  {id: 54, name: 'car-outline', class: ICON_CLASS.Ionicons},
  {id: 55, name: 'cart-outline', class: ICON_CLASS.Ionicons},
  {id: 56, name: 'cloud-outline', class: ICON_CLASS.Ionicons},
  {id: 57, name: 'code-sharp', class: ICON_CLASS.Ionicons},
  {id: 58, name: 'fast-food-outline', class: ICON_CLASS.Ionicons},
  {id: 59, name: 'film-outline', class: ICON_CLASS.Ionicons},
  {id: 60, name: 'flower-outline', class: ICON_CLASS.Ionicons},
  {id: 61, name: 'fitness-outline', class: ICON_CLASS.Ionicons},
  {id: 62, name: 'football-outline', class: ICON_CLASS.Ionicons},
  {id: 63, name: 'game-controller-outline', class: ICON_CLASS.Ionicons},
  {id: 64, name: 'golf-outline', class: ICON_CLASS.Ionicons},
  {id: 65, name: 'hammer-outline', class: ICON_CLASS.Ionicons},
  {id: 66, name: 'gift-outline', class: ICON_CLASS.Ionicons},
  {id: 67, name: 'headset-outline', class: ICON_CLASS.Ionicons},
  {id: 68, name: 'help-buoy-outline', class: ICON_CLASS.Ionicons},
  {id: 69, name: 'ice-cream-outline', class: ICON_CLASS.Ionicons},
  {id: 70, name: 'leaf-outline', class: ICON_CLASS.Ionicons},
  {id: 71, name: 'library-outline', class: ICON_CLASS.Ionicons},
  {id: 72, name: 'key-outline', class: ICON_CLASS.Ionicons},
  {id: 73, name: 'medkit-outline', class: ICON_CLASS.Ionicons},
  {id: 74, name: 'moon-outline', class: ICON_CLASS.Ionicons},
  {id: 75, name: 'musical-notes-outline', class: ICON_CLASS.Ionicons},
  {id: 76, name: 'musical-notes-outline', class: ICON_CLASS.Ionicons},
  {id: 77, name: 'pizza-outline', class: ICON_CLASS.Ionicons},
  {id: 78, name: 'planet-outline', class: ICON_CLASS.Ionicons},
  {id: 79, name: 'pricetags-outline', class: ICON_CLASS.Ionicons},
  {id: 80, name: 'receipt-outline', class: ICON_CLASS.Ionicons},
  {id: 81, name: 'restaurant-outline', class: ICON_CLASS.Ionicons},
  {id: 82, name: 'ribbon-outline', class: ICON_CLASS.Ionicons},
  {id: 83, name: 'rocket-outline', class: ICON_CLASS.Ionicons},
  {id: 84, name: 'skull-outline', class: ICON_CLASS.Ionicons},
  {id: 85, name: 'snow-outline', class: ICON_CLASS.Ionicons},
];

// const iconsData = icons.map((item) => {
//   return new TransactionCategoryIcon({id: item.id, name: item.name, class: item.class});
// });
export default icons;
